export const dummy_data = [
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "expenses",
    amount: "600",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "banana",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "expenses",
    amount: "600",
    source: "pendrive",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "investments",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "savings",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
];
