export const dummy_data = [
  {
    transactionType: "income",
    amount: "20",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "expenses",
    amount: "60",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "300",
    source: "banana",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "500",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "expenses",
    amount: "1200",
    source: "pendrive",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "investments",
    amount: "210",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "230",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "240",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "savings",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
  {
    transactionType: "income",
    amount: "200",
    source: "coffee",
    description: "I bought this on my way to school",
    date: "21/02/2021",
  },
];
